<?php
class Tgen_DnD_35MIC_Goods_B extends Tgen_DnD_35MIC_Goods {
    public $items = array(
        'bloodstone',
        'carnelian',
        'chalcedony',
        'chrysoprase',
        'citrine',
        'iolite',
        'jasper',
        'moonstone',
        'onyx',
        'peridot',
        'clear quartz',
        'sard',
        'sardonyx',
        'rose quartz',
        'smoky quartz',
        'star rose quartz',
        'zircon',
        'silver ewer',
        'carved bone statuette',
        'ivory statuette',
        'small gold bracelet',
        'bronze statue of a knight',
        'mahogany bust of a poet',
        'silver ring with blue quartz',
        'small perfume bottle of black crystal',
        'purple velvet gloves with silver stitching',
        'ornate wooden box',
        'bronze earrings set with ceramic ovals',
        'copper horn ringed with seashells',
        'oak candlestick',
        'mahogany tray carved with flowers',
        'rhinoceros-hide sack',
        'peacock-feather mask',
        'broad-brimmed velvet hat',
        'zircon-studded dancing slippers',
    );
    public $value = array(
        'dice' => 2,
        'type' => 4,
        'mult' => 10,
    );
} // end Tgen_DnD_35MIC_Goods_B